numpy:- numpy is an open source python library used for mathematical computation.

- for using numpy be used import numpy. 
- we also define alias for this (import numpy as np).
- for install numpy library be use pip install numpy.

# creating array using numpy...


In [4]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
arr

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

# for check type and shape, ndim,dtype,size


In [7]:
print(type(arr))
print(arr.shape)
print(arr.ndim)
print(arr.dtype)
print(arr.size)

<class 'numpy.ndarray'>
(5,)
1
int64
5


# reshaping...

In [10]:
arr.reshape(5,1) # convert row to column
arr.reshape(1,5) # convert column to row

[1 2 3 4 5]
[1 2 3 4 5]


# create an array by using arange built-in function. it take three parameter np.arange(start,end,steps)..

In [23]:
a=np.arange(0,20,2) # create an array of even numbers from 0 to 20 (exclusive) with a step of 2
print(a)

[ 0  2  4  6  8 10 12 14 16 18]


# for 2-d array(2 rows, 5 column)...


In [24]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2) # arr2 is a 2D array with 2 rows and 5 columns
print(arr2.shape) # shape is (2,5) because it has 2 rows and 5 columns
print(arr2.ndim) # ndim is 2 because it has 2 dimensions
print(arr2.dtype) # dtype is int64 because it contains integers
print("size of arr2:",arr2.size)# size is 10 because it has 10 elements (2 rows * 5 columns)
print(arr2.itemsize)# itemsize is 8 bytes because each integer takes 8 bytes of memory

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
2
int64
size of arr2: 10
8


# reshaping 2-d array...

In [17]:
arr2.reshape(5,2) # reshape arr2 to 5 rows and 2 columns

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

# creating different different dimension for 2-d array.......

In [28]:
array1=np.array([1,2,3]) # 1 rows only...1-d array
array2=np.array([[4,5,6],[7,8,9]])# 2 rows and 3 columns...2-d array
array3=np.array([[1,2,3,10],[4,5,6,11],[7,8,9,12]])# 3 rows and 4 columns...2-d array
print("1-d array",array1)
print("2-d array",array2)
print("2-d array",array3)   

1-d array [1 2 3]
2-d array [[4 5 6]
 [7 8 9]]
2-d array [[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


# numpy vectorized opertion


In [31]:
arr1=np.array([10,20,30,40,50])
arr2=np.array([5,15,20,25,30])

# element-wise addition
print(arr1+arr2) 

# element-wise subtraction
print(arr1-arr2)

# element-wise multiplication
print(arr1*arr2)

# element-wise division
print(arr1/arr2)

[15 35 50 65 80]
[ 5  5 10 15 20]
[  50  300  600 1000 1500]
[2.         1.33333333 1.5        1.6        1.66666667]


# numpy universal function used for whole array..

In [37]:
arr1=np.array([1,2,3,4,5])

# calculate the mean of arr1
print("square root: ",np.sqrt(arr1))

# calculate the exponential of arr1
print("exponential: ",np.exp(arr1))

# calculate the logarithm of arr1
print("logarithm: ",np.log(arr1))

# calculate the sine of arr1
print("sine: ",np.sin(arr1))

# calculate the cosine of arr1
print("cosine: ",np.cos(arr1))

# like using same synatax just by changing bulit-in function 
# we can find mean, median, standard deviation, variance, etc. 
# using numpy functions

square root:  [1.         1.41421356 1.73205081 2.         2.23606798]
exponential:  [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
logarithm:  [0.         0.69314718 1.09861229 1.38629436 1.60943791]


# array slicing and indexing..


In [47]:
arr=np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

# indexing......
print(arr[0][0]) # access the element in the first row and first column (1)
print(arr[2][2])

# slicing......
print(arr[1:,2:]) # access the first 2 rows and first 3 columns

print(arr[0:2,2:]) # access the first 2 rows and first 3 columns

print(arr[0:,3:])
print(arr[1:,1:3])

1
11
[[ 7  8]
 [11 12]]
[[3 4]
 [7 8]]
[[ 4]
 [ 8]
 [12]]
[[ 6  7]
 [10 11]]


# modify 1-d array....


In [49]:
arr=np.array([1,2,3,4,5])
arr[0]=10
print(arr)

[10  2  3  4  5]


# modify 2-d array..

In [50]:
arr2=np.array([[1,2,3],
               [4,5,6]])
arr2[1][1]=25
print(arr2)

[[ 1  2  3]
 [ 4 25  6]]


# statistical concept-normalization
# to have a mean of 0 and s.d of 1

In [52]:
data=np.array([1,2,3,4,5])

# calculate the mean of data and s.d
mean=np.mean(data)
std_dev=np.std(data)

# normalization the data...
normalized_data=(data-mean)/std_dev
print("normalized data: ",normalized_data)

normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
